version: '3.4'
services:
  mysql:
    image: 'mysql:8'
    environment:
      - MYSQL_ROOT_PASSWORD=therootpassword
      - MSQL_DATABASE=status_for_systems
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3308:3306"
    volumes:
      - mysql:/var/lib/mysql
  status-for-systems-app:
    env_file:
      - docker/environments/local.env
    build:
      context: .
      dockerfile: docker/Dockerfile.dev
    volumes:
      - /app/node_modules
      - .:/app
    command: "npm run start:debug"

volumes:
  mysql: {}