version: '3.4'
services:
  mysql:
    image: 'mysql:8'
    environment:
      - MYSQL_ROOT_PASSWORD=therootpassword
      - MYSQL_DATABASE=status_for_systems
      - MYSQL_ROOT_HOST=%
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3308:3306"
    volumes:
      - mysql:/var/lib/mysql
  api:
    env_file:
      - docker/environments/local.env
    ports:
      - 8080:8080
    build:
      context: api
      dockerfile: ../docker/go.Dockerfile.dev
    volumes:
      - ./api:/app

volumes:
  mysql: {}