name: Deploy Docs

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies from requirements.txt
        run: |
          pip install -r docs/requirements.txt


      - name: Deploy to gh-pages branch
        working-directory: docs
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Auth for git push
          GIT_COMMITTER_NAME: github-actions
          GIT_COMMITTER_EMAIL: github-actions@github.com
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          mkdocs gh-deploy --force --clean